export enum AccountKind {
  ORGANIZATION = 'ORGANIZATION',
  PERSON = 'PERSON',
}

export enum CustomerSegment {
  B2B = 'B2B',
  B2C = 'B2C',
}

export enum AccountType {
  DEALER = 'DEALER',
  SHOWROOM = 'SHOWROOM',
  B2B_CUSTOMER = 'B2B_CUSTOMER',
  B2C_CUSTOMER = 'B2C_CUSTOMER',
  ONLINE_CUSTOMER = 'ONLINE_CUSTOMER',
  PARTNER = 'PARTNER',
  INDIVIDUAL = 'INDIVIDUAL',
  COMPANY = 'COMPANY',
}

export enum AccountStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum RecordStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum AddressType {
  BILLING = 'BILLING',
  SHIPPING = 'SHIPPING',
  BUSINESS_LOCATION = 'BUSINESS_LOCATION',
  REGISTERED_OFFICE = 'REGISTERED_OFFICE',
  WAREHOUSE = 'WAREHOUSE',
  SHOWROOM = 'SHOWROOM',
  BRANCH = 'BRANCH',
  OTHER = 'OTHER',
}

export enum ContactRole {
  OWNER = 'OWNER',
  PURCHASING = 'PURCHASING',
  ACCOUNTING = 'ACCOUNTING',
  TECHNICAL = 'TECHNICAL',
  SALES = 'SALES',
  WAREHOUSE = 'WAREHOUSE',
  OTHER = 'OTHER',
}

export enum ClassificationType {
  CUSTOMER_TYPE = 'CUSTOMER_TYPE',
  CHANNEL = 'CHANNEL',
  SEGMENT = 'SEGMENT',
  STATUS_TAG = 'STATUS_TAG',
  PARTNER_TYPE = 'PARTNER_TYPE',
}

export enum AccountRelationshipType {
  PARENT_CHILD = 'PARENT_CHILD',
  HEAD_OFFICE_BRANCH = 'HEAD_OFFICE_BRANCH',
  GROUP_MEMBER = 'GROUP_MEMBER',
  REGION_MEMBER = 'REGION_MEMBER',
  BILL_TO = 'BILL_TO',
  SHIP_TO = 'SHIP_TO',
  MANAGED_BY = 'MANAGED_BY',
}
