import {
  AccountKind,
  AccountStatus,
  AccountType,
  AddressType,
  ClassificationType,
  ContactRole,
  CustomerSegment,
  RecordStatus,
} from './customer-account.enums';
import type { CreateCustomerAccountRequest } from './customer-account.models';

const now = '2026-05-04T07:00:00.000Z';

export const initialCustomerAccounts = [
  {
    accountNumber: 'ACC-000246',
    customerCode: 'GRP-MIEN-BAC',
    accountName: 'Everon Northern Dealer Group',
    accountKind: AccountKind.ORGANIZATION,
    customerSegment: CustomerSegment.B2B,
    accountType: AccountType.COMPANY,
    status: AccountStatus.ACTIVE,
    phone: '024 3900 1000',
    regionCode: 'HN',
    territoryCode: 'MB',
    businessProfile: {
      legalName: 'Everon Northern Dealer Group',
      dealerTier: 'A+',
      dealerType: 'Regional group',
      regionCode: 'HN',
      territoryCode: 'MB',
      createdAt: now,
      updatedAt: now,
    },
    contacts: [
      {
        fullName: 'Northern Group Admin',
        contactRole: ContactRole.OWNER,
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    externalReferences: [
      {
        sourceSystem: 'CRM',
        externalId: 'SF-GRP-NORTH',
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    classifications: [
      {
        classificationType: ClassificationType.CUSTOMER_TYPE,
        classificationCode: 'A+',
        classificationName: 'Regional Group',
        isPrimary: true,
      },
    ],
  },
  {
    accountNumber: 'ACC-000247',
    customerCode: 'GRP-MIEN-NAM',
    accountName: 'Everon Southern Dealer Group',
    accountKind: AccountKind.ORGANIZATION,
    customerSegment: CustomerSegment.B2B,
    accountType: AccountType.COMPANY,
    status: AccountStatus.ACTIVE,
    phone: '028 3900 1000',
    regionCode: 'HCM',
    territoryCode: 'MN',
    businessProfile: {
      legalName: 'Everon Southern Dealer Group',
      dealerTier: 'A',
      dealerType: 'Regional group',
      regionCode: 'HCM',
      territoryCode: 'MN',
      createdAt: now,
      updatedAt: now,
    },
    contacts: [
      {
        fullName: 'Southern Group Admin',
        contactRole: ContactRole.OWNER,
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    externalReferences: [
      {
        sourceSystem: 'CRM',
        externalId: 'SF-GRP-SOUTH',
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    classifications: [
      {
        classificationType: ClassificationType.CUSTOMER_TYPE,
        classificationCode: 'A',
        classificationName: 'Regional Group',
        isPrimary: true,
      },
    ],
  },
  {
    accountNumber: 'ACC-000248',
    customerCode: 'DL-HN-0001',
    accountName: 'Dai ly Everon Hoan Kiem',
    accountKind: AccountKind.ORGANIZATION,
    customerSegment: CustomerSegment.B2B,
    accountType: AccountType.DEALER,
    status: AccountStatus.ACTIVE,
    parentCustomerCode: 'GRP-MIEN-BAC',
    phone: '024 3826 1999',
    email: 'hoankiem@everon.vn',
    taxCode: '0101234567',
    regionCode: 'HN',
    territoryCode: 'HN-01',
    businessProfile: {
      legalName: 'Cong ty TNHH Noi That Hoan Kiem',
      taxCode: '0101234567',
      industry: 'Retail bedding',
      paymentTerm: 'Net 30',
      creditLimit: 1200000000,
      dealerTier: 'A+',
      dealerType: 'Flagship dealer',
      regionCode: 'HN',
      territoryCode: 'HN-01',
      createdAt: now,
      updatedAt: now,
    },
    contacts: [
      {
        fullName: 'Nguyen Minh Anh',
        mobile: '0903 456 789',
        email: 'anh.nguyen@everon.vn',
        contactRole: ContactRole.OWNER,
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    addresses: [
      {
        addressType: AddressType.SHOWROOM,
        addressName: 'Showroom Hoan Kiem',
        line1: '28 Hang Bong',
        district: 'Hoan Kiem',
        province: 'Ha Noi',
        country: 'Vietnam',
        isDefault: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    externalReferences: [
      {
        sourceSystem: 'CRM',
        externalId: 'SF-001928',
        externalCode: 'CRM-HN-0001',
        isPrimary: true,
        status: RecordStatus.ACTIVE,
        lastSyncedAt: now,
      },
      {
        sourceSystem: 'EVERON',
        externalId: 'EVR-HN001',
        isPrimary: false,
        status: RecordStatus.ACTIVE,
      },
      {
        sourceSystem: 'KINGKOIL',
        externalId: 'KK-HN018',
        isPrimary: false,
        status: RecordStatus.ACTIVE,
      },
    ],
    classifications: [
      {
        classificationType: ClassificationType.CUSTOMER_TYPE,
        classificationCode: 'A+',
        classificationName: 'Strategic Dealer',
        isPrimary: true,
      },
    ],
  },
  {
    accountNumber: 'ACC-000249',
    customerCode: 'SR-DN-0032',
    accountName: 'Showroom Everon Da Nang',
    accountKind: AccountKind.ORGANIZATION,
    customerSegment: CustomerSegment.B2B,
    accountType: AccountType.SHOWROOM,
    status: AccountStatus.PENDING,
    phone: '0236 355 6688',
    regionCode: 'DN',
    territoryCode: 'MT-02',
    businessProfile: {
      legalName: 'Chi nhanh Everon Da Nang',
      dealerTier: 'A',
      dealerType: 'Company showroom',
      regionCode: 'DN',
      territoryCode: 'MT-02',
      creditLimit: 600000000,
      paymentTerm: 'Net 15',
      createdAt: now,
      updatedAt: now,
    },
    contacts: [
      {
        fullName: 'Tran Quoc Bao',
        mobile: '0912 222 888',
        contactRole: ContactRole.SALES,
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    addresses: [
      {
        addressType: AddressType.BUSINESS_LOCATION,
        addressName: 'Da Nang showroom',
        line1: '118 Nguyen Van Linh',
        district: 'Hai Chau',
        province: 'Da Nang',
        country: 'Vietnam',
        isDefault: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    externalReferences: [
      {
        sourceSystem: 'EVERON',
        externalId: 'EVR-DN032',
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
      {
        sourceSystem: 'KIOTVIET',
        externalId: 'KV-DN-3321',
        isPrimary: false,
        status: RecordStatus.ACTIVE,
        lastSyncedAt: '2026-05-03T11:15:00.000Z',
      },
    ],
    classifications: [
      {
        classificationType: ClassificationType.CUSTOMER_TYPE,
        classificationCode: 'A',
        classificationName: 'Showroom',
        isPrimary: true,
      },
    ],
  },
  {
    accountNumber: 'ACC-000252',
    customerCode: 'B2C-HCM-0911',
    accountName: 'Le Thanh Mai',
    accountKind: AccountKind.PERSON,
    customerSegment: CustomerSegment.B2C,
    accountType: AccountType.INDIVIDUAL,
    status: AccountStatus.ACTIVE,
    phone: '0988 777 123',
    email: 'mai.le@example.com',
    regionCode: 'HCM',
    territoryCode: 'HCM-03',
    personProfile: {
      firstName: 'Mai',
      lastName: 'Le Thanh',
      personalEmail: 'mai.le@example.com',
      personalMobile: '0988 777 123',
      loyaltyId: 'LOY-923811',
      preferredChannel: 'Zalo',
      gender: 'Female',
      createdAt: now,
      updatedAt: now,
    },
    addresses: [
      {
        addressType: AddressType.SHIPPING,
        addressName: 'Home',
        line1: '14 Nguyen Trai',
        district: 'Quan 5',
        province: 'Ho Chi Minh',
        country: 'Vietnam',
        isDefault: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    externalReferences: [
      {
        sourceSystem: 'LOYALTY',
        externalId: 'LOY-923811',
        isPrimary: true,
        status: RecordStatus.ACTIVE,
        lastSyncedAt: '2026-05-02T03:45:00.000Z',
      },
    ],
    classifications: [
      {
        classificationType: ClassificationType.SEGMENT,
        classificationCode: 'B2C',
        classificationName: 'Online customer',
        isPrimary: true,
      },
    ],
  },
  {
    accountNumber: 'ACC-000253',
    customerCode: 'DL-HCM-0048',
    accountName: 'Dai ly Kingkoil Quan 7',
    accountKind: AccountKind.ORGANIZATION,
    customerSegment: CustomerSegment.B2B,
    accountType: AccountType.DEALER,
    status: AccountStatus.SUSPENDED,
    parentCustomerCode: 'GRP-MIEN-NAM',
    phone: '028 3777 4488',
    regionCode: 'HCM',
    territoryCode: 'HCM-07',
    businessProfile: {
      legalName: 'Cong ty TNHH Nem Quan 7',
      taxCode: '0312345678',
      dealerTier: 'B+',
      dealerType: 'Dealer',
      creditLimit: 400000000,
      paymentTerm: 'Prepaid',
      regionCode: 'HCM',
      territoryCode: 'HCM-07',
      createdAt: now,
      updatedAt: now,
    },
    contacts: [
      {
        fullName: 'Pham Gia Huy',
        mobile: '0938 661 661',
        contactRole: ContactRole.ACCOUNTING,
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    externalReferences: [
      {
        sourceSystem: 'KINGKOIL',
        externalId: 'KK-HCM048',
        isPrimary: true,
        status: RecordStatus.ACTIVE,
      },
    ],
    classifications: [
      {
        classificationType: ClassificationType.CUSTOMER_TYPE,
        classificationCode: 'B+',
        classificationName: 'Dealer',
        isPrimary: true,
      },
    ],
  },
] satisfies CreateCustomerAccountRequest[];
